### ISSUE TITLE
Android allway theme Light

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [brminnick/DarkModeSplashScreen#2]
I run your sample code: Android allway theme Light. But  iOS working correctly!
I use my Phone Android 9 and Genymotion API 28

**Comment by brminnick** [comment]
Hi @nguyenthanhliemfc!

Android implemented Dark Theme in API 29: https://developer.android.com/guide/topics/ui/look-and-feel/darktheme

**Comment by nguyenthanhliemfc** [comment]
@brminnick Thanks!
