### ISSUE TITLE
[Question] Custom color on background

### ISSUE THREAD

**Issue by Abesoddy** [brminnick/DarkModeSplashScreen#3]
Hello, 

Thanks for this git repository!

However I wanted to know if it is possible to put a custom color in the background especially in the ios storyboard?

**Comment by brminnick** [comment]
Yup! In your Asset Catalog (`Assets.xcassets`), create a New Color Set. In that Color Set, you can define any color you want for Light Mode and any color you want for Dark Mode! 

Here's some screenshots of doing it in Visual Studio for Mac:

<img width="611" alt="Screen Shot 2020-09-15 at 8 46 01 AM" src="https://user-images.githubusercontent.com/13558917/93233479-f8ec9800-f72f-11ea-8f8a-b17f6535fe0c.png">

![ScreenFlow](https://user-images.githubusercontent.com/13558917/93233491-fe49e280-f72f-11ea-879c-ddb49f02cd72.gif)

**Comment by brminnick** [comment]
By the way - the app in the screenshots is open-source.

Feel free to download/clone it to see how I used these custom colors in GitTrends:
https://github.com/brminnick/GitTrends
